name: Deploy Pages
on:
  push:
    branches: [ gh-pages ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "🎉 Deployment Completed!" > ./status.txt